version: "3.8"

services:
  backend:
    container_name: backend
    image: backend-node
    build:
      context: .
    volumes:
      - .:/app
      - dependencies:/app/node_modules
    env_file:
      - .env
    ports:
      - 4000:4000
    depends_on:
        - db

  db:
    image: postgres:12
    container_name: db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  dependencies:
  postgres:
