name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.0

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check for lint errors
        run: yarn lint

      - name: Run tests for web
        run: cd web && yarn test

      - name: Run tests for backend
        run: cd backend && yarn test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.0

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build:web && yarn build:backend
